### ISSUE TITLE
Replacement fails when strings include binary characters (e.g. `\xE9`)

### ISSUE THREAD

**Issue by bglimepoint** [jedld/multi_string_replace#9]
Hello :-)

We're using multi_string_replace, and it's been great so far - thanks :-)

We have some data that's gotten into our replace and it's causing a segfault whenever the replace is executed.

We've narrowed it down to an example of `MultiStringReplace.replace("", "\xE9"=>"")` crashing.

We'll keep looking into it (as best we can), but thought we'd create the issue whilst investigating :-)

**Comment by jedld** [comment]
Thanks for this. let me try to reproduce it and merge it as soon as I can.
